#!/bin/sh

[ $(pamixer --get-mute) = true ] && echo MUTE && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="VOL: "
elif [ "$vol" -lt "30" ]; then
	icon="vol: "
else
	icon="VoL: "
fi

echo "$icon$vol%"
